
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: root
  application:
    name: product
  zipkin:
    base-url: http://10.200.132.144::9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
server:
  port: 8082
env:
  dev
label:
  dev

